### ISSUE TITLE
Error execution task 'androidCheckstyle'

### ISSUE THREAD

**Issue by johnkil** [noveogroup/android-check#11]
I do not understand what could be the problem ((

Output:

```
Error:Execution failed for task ':app:androidCheckstyle'.
> Ambiguous method overloading for method java.util.jar.JarFile#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
    [class java.io.File]
    [class java.lang.String]
```

**Comment by Armaxis** [comment]
I also got this error and after several hours of investigation I found out what's the issue.

You get this error only if you place 

```
dependencies { 
    classpath 'com.noveogroup.android:check:1.1.2
}
```

in  **module's** `build.gradle` , instead of **project's** `build.gradle`

So a workaround would be moving this dependency to project's `build.gradle`

Picture for clarity:
![Image](http://i.imgur.com/QzzKZlJ.png)

**Comment by johnkil** [comment]
:thumbsup:

**Comment by igelgrun** [comment]
Now you can put dependencies in any build file: both in `<root>/build.gradle` and `<root>/app/build.gradle`.
